### ISSUE TITLE
Confirm submit when not all letters placed

### ISSUE THREAD

**Issue by wshaver** [nickzuber/cross-wordle#4]
Accidently hit submit instead of a letter. Would be great to get a confirmation prompt instead of ending the game abruptly. :(

Thanks for the fun game.

**Comment by nickzuber** [comment]
Hey sorry for the late reply — that's a good idea, I actually ran into the same issue a few times (it's so easy to hit that button by mistake).

Next update I'll try to incorporate something! Thanks for the tip 😄

**Comment by nickzuber** [comment]
Only a few years later..... I have good news!

Crosswordle has rebranded to Scrambed and can now be found here → https://github.com/nickzuber/scrambled or https://play-scrambled.com/

Many little improvements like this have been added there 🙂
