### ISSUE TITLE
Share option shouldn’t share solution 

### ISSUE THREAD

**Issue by jpem27** [nickzuber/cross-wordle#8]
If I’m sharing this with someone I don’t want to send them a picture of my solution. A better way to do this would be like Wordle where you generate a text string with emojis and copy it to the clipboard. 

Something like the below (where the first two hard returns are so the user can type their message to who they are sharing it with, followed by their score.

“

Crosswordle #[number]:
X / 20
🟢🟢🟢🟢🟢🟢
🟢⚪️🟢⚪️⚪️🟢
🟢⚪️🟢⚪️⚪️🟢
🟢⚪️🟢⚪️⚪️⚪️
🟢⚪️🟢⚪️⚪️⚪️
⚪️🟢🟢🟢🟢⚪️
“

**Comment by nickzuber** [comment]
Great suggestion!

Crosswordle has rebranded to Scrambed and can now be found here → https://github.com/nickzuber/scrambled or https://play-scrambled.com/

Many little improvements like this has been added that 🙂
